export const initialBands = [
  'Accacio Avenue (Lord Vigo & AA)',
  'Aegror',
  'Age Of Arcadia',
  'AlleHackbar',
  'Alltheniko',
  'Askväder (Daredevil Records)',
  'Assassin',
  'Atomgott',
  'Bad Butler',
  'Bassomanic',
  'Black Eden',
  'Blakylle',
  'Blood Fire Death',
  'Booze Control',
  'Budapester Puppenmuseum',
  'Burning Amp',
  'Bütcher (Roadmaster Booking)',
  'Cavemen (Daredevil Records)',
  'Chasing Death',
  'Chopstick Killer',
  'Christmas',
  'Corbian',
  'Creed of Pain',
  'Dead Mans Boogie',
  'Deadly Sin',
  'Deamon Incarnate (Daredevil Records)',
  'Dedpool',
  'Der rote Milan (Ichor und der Rote Milan)',
  'Diamond Head',
  'Disbelief',
  'Disinfect',
  'Divine Zero',
  'Dust Bolt (Rodeostar Booking)',
  'Dying Gorgeous Lies',
  'Earthgrave',
  'Edge of Thorns',
  'Engel (Napalm Records)',
  'Entory',
  'Epsilon',
  'Erasement',
  'Existance',
  'Fatal Embrace',
  'Formosa',
  'From Fall To Spring',
  'Fusion Bomb',
  'Gun Barrel',
  'Grande Massive (Daredevil Records)',
  'Hate Squad (Rodeostar Booking)',
  'Herediatry',
  'Hopelezz',
  'Horseman',
  'Ichor (Ichor und der Rote Milan)',
  'Ignotion',
  'Indian Nightmare (Roadmaster Booking)',
  'Inzest',
  'Iron Angel',
  'Iron Horses',
  'Ironbite',
  'Iron Angel (Roadmaster Booking)',
  'Konvent (Napalm Records)',
  'Kingdom of Salvation',
  'Kraton',
  'Kuenring',
  'Liveware',
  'Little Vilians (Daredevil Records, UK + L.A)',
  'Lord Vigo (Lord Vigo & AA)',
  'Maahes',
  'Made in Iron (Daredevil Records, Maiden Tribute)',
  'Materia',
  'Messenger',
  'Mind Patrol (Schweiz)',
  'Mindpatrol (Deutsch)',
  'Mollust',
  'Neorite',
  'Nepumuc',
  'Night Laser',
  'Nightbearer',
  'Oceans (Rodeostart Booking)',
  'Odium',
  'Ophis (Roadmaster Records)',
  'Ordos (Daredevil Records)',
  'Ox',
  'Philosohical Warlords',
  'Precipiation',
  'Project Renegade (GRE)',
  'Psychophant',
  'Razorblad Messiah',
  'Red Raven',
  'Rezet (Rodeostar Booking)',
  'Riot in the Attic',
  'Silbergerät',
  'Sisters of Suffocation (Napalm Records)',
  'Slaughterday',
  'Solar Fragment',
  'Spite Fuel',
  'Spy # Row',
  'Stallion',
  'Stone Blind',
  'Street Fighter',
  'Süßer Hase Bommel',
  'Shuulak',
  'Tempest',
  'The Darker My Horizon (UK)',
  'The FALS',
  'The Flesh Trading Company',
  'The Legion Ghost',
  'The National Orchestra of the United Kindom of Goats',
  'The Rough Edges',
  'Torian',
  'Turin Horse',
  'Traitor (Rodeostar Booking)',
  'Tyrmfar',
  'Ungoliantha',
  'Ventura',
  'Voldt',
  'Wanted Inc',
  'Warfield',
  'White Mantis'
];
